services:
  db:
    image: postgres:16
    container_name: pomodoro_db
    environment:
      POSTGRES_DB: pomodoro
      POSTGRES_USER: pomodoro
      POSTGRES_PASSWORD: pomodoro
    ports:
      - "5432:5432"
    volumes:
      - pomodoro_pgdata:/var/lib/postgresql/data

volumes:
  pomodoro_pgdata:
